M48
; DRILL file {KiCad 7.0.9} date zo 31 dec 2023 17:17:47 CET
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-12-31T17:17:47+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.9
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0866
%
G90
G05
T1
X4.0551Y-1.2835
X4.0551Y-4.2913
X6.0472Y-1.2835
X6.0472Y-4.2913
T0
M30
